### ISSUE TITLE
Checks fail with duckplyr

### ISSUE THREAD

**Issue by krlmlr** [JacobIMarsh/crosshap#6] opened 2024-10-28 20:37 UTC
The duckplyr package is aimed to be a drop-in replacement for dplyr, with full behavior compatibility. To assert that, I'm running checks with a rigged version of dplyr. This package fails its checks in this scenario.

Details: https://github.com/krlmlr/dplyr/blob/f-revdep-duckplyr/revdep/problems.md .

Learn more about duckplyr: https://duckplyr.tidyverse.org/ .

From the error message, I can't tell immediately what the cause of the failure is. I'd appreciate your help: can you please help digest a reproducible example that shows how duckplyr is behaving differently from dplyr in your use case?

The modified dplyr version can be installed with any of:

```r
pak::pak("krlmlr/dplyr@f-revdep-duckplyr")
# remotes::install_github("krlmlr/dplyr@f-revdep-duckplyr")
# devtools::install_github("krlmlr/dplyr@f-revdep-duckplyr")
```

Thanks a lot for your help! Please let me know if you have any questions.

Tracker: https://github.com/tidyverse/duckplyr/issues/297.

**Comment by jacobimarsh** [comment] 2024-10-29 14:17
Will try roll into next set of changes, thanks!

**Comment by krlmlr** [comment] 2024-10-29 20:56
Thanks, Jacob! There's no need to change your package because it works with dplyr; I'd like to understand why duckplyr doesn't work with your package.

**Comment by jacobimarsh** [comment] 2024-10-30 16:52
Hmm okay I just installed the modified dplyr and tried to run it. So the error is in a test for a non-core component of the crosshap package, and the results it gives with both dplyrs (1.4.1.999 and 1.4.1) are precisely same - and are correct from looking at the output plot, although the test is based on the NA count in the tibble of the plotted data and is giving slightly different output to what it expects.

The difference seems to be somewhere in the clustering and data processing, and it seems arbitrary, I'll update the test expected values in the next version of crosshap, but **rest assured, duckplyr looks like its working as intended**, the (superficial) problem seems to be due to something else!

**Comment by krlmlr** [comment] 2024-10-31 21:48
Thanks. If it behaves differently, it's not a drop-in replacement... Could be that some other package used in this process gives different results, I'd be very much interested in details here. Also, I recently updated this branch because I fixed a problem with `if_else()` -- could be that the results are different now, although I still see the same results with crosshap.

**Comment by jacobimarsh** [comment] 2024-11-01 16:14
Okay I had another look this morning, I think I know what's going on, it's one of two things:

1. The test that was failing didn't have a function explicitly defined, fixed now
2. The error message from your test seems to be due to the way in which crosshap's tests are set up. As in, there are functions called outside of the test's scope, i.e. it is called before the test is called. It could likely be fixed by calling the function within the test but as it's how I wrote all the tests and it isn't an issue when I run checks or push to github, I'm going to leave it for now.

`result <- function`
`test_that(
{result}
)`

as opposed to:
`test_that(
{result <- function;
result}
)`

Probably different versions of testing software

**Closed as completed** 2024-11-04 21:55 UTC
